export const DASHBOARD_MENUS = {
  supplier: {
    title: 'Supplier',
    accent: 'from-blue-700 via-blue-900 to-slate-950',
    description: 'Real-time milk quality monitoring',
    items: [
      { id: 'overview', label: 'Dashboard' },
      { id: 'submit',   label: 'Submit Reading' },
      { id: 'live', label: 'Live Sensors' },
      { id: 'records', label: 'Records' },
      { id: 'alerts', label: 'Alerts' },
      { id: 'reports', label: 'Reports' },
      { id: 'search', label: 'Search' },
      { id: 'profile', label: 'Profile' },
      { id: 'settings', label: 'Settings' },
    ],
  },
  seller: {
    title: 'Seller',
    accent: 'from-emerald-700 via-blue-900 to-slate-950',
    description: 'Decision support and inventory insights',
    items: [
      { id: 'overview', label: 'Dashboard' },
      { id: 'inventory', label: 'Inventory' },
      { id: 'decision', label: 'Decision Support' },
      { id: 'trends', label: 'Trends' },
      { id: 'records', label: 'Records' },
      { id: 'alerts', label: 'Alerts' },
      { id: 'reports', label: 'Reports' },
      { id: 'search', label: 'Search' },
      { id: 'profile', label: 'Profile' },
      { id: 'settings', label: 'Settings' },
    ],
  },
  admin: {
    title: 'Admin',
    accent: 'from-slate-800 via-blue-950 to-indigo-950',
    description: 'System control and operational oversight',
    items: [
      { id: 'overview', label: 'Dashboard' },
      { id: 'users', label: 'Users' },
      { id: 'records', label: 'All Records' },
      { id: 'alerts', label: 'Alerts' },
      { id: 'logs', label: 'System Logs' },
      { id: 'reports', label: 'Reports' },
      { id: 'search', label: 'Search' },
      { id: 'settings', label: 'Settings' },
    ],
  },
};
